config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root "lists#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

    def self.search(query)
        list = List.where("country like ?", "%" + query + "%")
        if list
            list
        else
            List.all
        end
    end

    def self.filter_two(query1,query2)
        List.where(region: query1, income_level:query2)
    end

    def self.filter_income(query)
        List.where(income_level: query)
    end

    def self.filter_region(query)
        List.where(region: query)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_list, only: %i[ show ]#edit update destroy ]
  
  # GET /lists or /lists.json
  def index
    if params[:sort].present? && params[:region].present? && params[:income_level].present?
      @lists = List.filter_two(params[:region],params[:income_level]).order(sort_column + " " + sort_direction)
    elsif params[:region].present? && params[:income_level].present?
      @lists = List.filter_two(params[:region],params[:income_level])
    elsif params[:region].present? && params[:sort].present?
      @lists = List.filter_region(params[:region]).order(sort_column + " " + sort_direction)
    elsif params[:region].present?
      @lists = List.filter_region(params[:region])
    elsif params[:income_level].present? && params[:sort].present?
      @lists = List.filter_income(params[:income_level]).order(sort_column + " " + sort_direction)
    elsif params[:income_level].present?
      @lists = List.filter_income(params[:income_level])
    elsif params[:search].present? && params[:sort].present?
      @lists = List.search(params[:search]).order(sort_column + " " + sort_direction)
    elsif params[:search].present?
      @lists = List.search(params[:search])
    elsif params[:sort].present?
      @lists = List.order(sort_column + " " + sort_direction)
    else
      @lists = List.all
    end
    #DirectionClass.changedir
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def sort_column
      List.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:CountryCode, :Country, :Region, :IncomeLevel, :Average, :YearMin, :Min, :YearMax, :Max, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, request.query_parameters.merge({sort: column, direction: direction})
        #link_to title, {:sort => column, :direction => direction}#, {:class => css_class}
      end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubySite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :income_level %>
    <%= form.text_field :income_level %>
  </div>

  <div class="field">
    <%= form.label :average %>
    <%= form.text_field :average %>
  </div>

  <div class="field">
    <%= form.label :year_min %>
    <%= form.number_field :year_min %>
  </div>

  <div class="field">
    <%= form.label :min %>
    <%= form.text_field :min %>
  </div>

  <div class="field">
    <%= form.label :year_max %>
    <%= form.number_field :year_max %>
  </div>

  <div class="field">
    <%= form.label :max %>
    <%= form.text_field :max %>
  </div>

  <div class="field">
    <%= form.label :year_one %>
    <%= form.text_field :year_one %>
  </div>

  <div class="field">
    <%= form.label :year_two %>
    <%= form.text_field :year_two %>
  </div>

  <div class="field">
    <%= form.label :year_three %>
    <%= form.text_field :year_three %>
  </div>

  <div class="field">
    <%= form.label :year_four %>
    <%= form.text_field :year_four %>
  </div>

  <div class="field">
    <%= form.label :year_five %>
    <%= form.text_field :year_five %>
  </div>

  <div class="field">
    <%= form.label :year_six %>
    <%= form.text_field :year_six %>
  </div>

  <div class="field">
    <%= form.label :year_seven %>
    <%= form.text_field :year_seven %>
  </div>

  <div class="field">
    <%= form.label :year_eight %>
    <%= form.text_field :year_eight %>
  </div>

  <div class="field">
    <%= form.label :year_nine %>
    <%= form.text_field :year_nine %>
  </div>

  <div class="field">
    <%= form.label :year_ten %>
    <%= form.text_field :year_ten %>
  </div>

  <div class="field">
    <%= form.label :year_eleven %>
    <%= form.text_field :year_eleven %>
  </div>

  <div class="field">
    <%= form.label :year_twelve %>
    <%= form.text_field :year_twelve %>
  </div>

  <div class="field">
    <%= form.label :year_thirteen %>
    <%= form.text_field :year_thirteen %>
  </div>

  <div class="field">
    <%= form.label :year_fourteen %>
    <%= form.text_field :year_fourteen %>
  </div>

  <div class="field">
    <%= form.label :year_fiveteen %>
    <%= form.text_field :year_fiveteen %>
  </div>

  <div class="field">
    <%= form.label :year_sixteen %>
    <%= form.text_field :year_sixteen %>
  </div>

  <div class="field">
    <%= form.label :year_seventeen %>
    <%= form.text_field :year_seventeen %>
  </div>

  <div class="field">
    <%= form.label :year_eighteen %>
    <%= form.text_field :year_eighteen %>
  </div>

  <div class="field">
    <%= form.label :year_nineteen %>
    <%= form.text_field :year_nineteen %>
  </div>

  <div class="field">
    <%= form.label :year_twenty %>
    <%= form.text_field :year_twenty %>
  </div>

  <div class="field">
    <%= form.label :year_twentyone %>
    <%= form.text_field :year_twentyone %>
  </div>

  <div class="field">
    <%= form.label :year_twentytwo %>
    <%= form.text_field :year_twentytwo %>
  </div>

  <div class="field">
    <%= form.label :year_twentythree %>
    <%= form.text_field :year_twentythree %>
  </div>

  <div class="field">
    <%= form.label :year_twentyfour %>
    <%= form.text_field :year_twentyfour %>
  </div>

  <div class="field">
    <%= form.label :year_twentyfive %>
    <%= form.text_field :year_twentyfive %>
  </div>

  <div class="field">
    <%= form.label :year_twentysix %>
    <%= form.text_field :year_twentysix %>
  </div>

  <div class="field">
    <%= form.label :year_twentyseven %>
    <%= form.text_field :year_twentyseven %>
  </div>

  <div class="field">
    <%= form.label :year_twentyeight %>
    <%= form.text_field :year_twentyeight %>
  </div>

  <div class="field">
    <%= form.label :year_twentynine %>
    <%= form.text_field :year_twentynine %>
  </div>

  <div class="field">
    <%= form.label :year_thirty %>
    <%= form.text_field :year_thirty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Climate Data</h1>

<%= form_tag lists_path, method: :get do %>
  <%= label_tag :search %>
  <%= text_field_tag "search", nil, placeholder:"Find country" %>
  <%= select_tag "income_level", options_for_select([nil,'Low income','Lower middle income','Upper middle income','High income'],nil) %>
  <%= select_tag "region", options_for_select([nil,'Africa Eastern and Southern','Africa Western and Central','East Asia & Pacific','Europe & Central Asia','Latin America & Caribbean','Middle East & North Africa','North America','South Asia','Sub-Saharan Africa'],nil) %>
  <%= submit_tag "search"%>
<% end %>

<%= link_to 'Clear', lists_path %>


<table>
  <thead>
    <tr>
      <th><%= sortable "country", "Country" %></th>
      <th><%= sortable "country_code", "Country code" %></th>
      <th><%= sortable "region", "Region" %></th>
      <th><%= sortable "income_level", "Income level" %></th>
      <th><%= sortable "average", "Average" %></th>
      <th><%= sortable "year_min", "Lowest year" %></th>
      <th><%= sortable "min", "Min" %></th>
      <th><%= sortable "year_max", "Highest year" %></th>
      <th><%= sortable "max", "Max" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.country %></td>
        <td><%= list.country_code %></td>
        <td><%= list.region %></td>
        <td><%= list.income_level %></td>
        <td><%= list.average %></td>
        <td><%= list.year_min %></td>
        <td><%= list.min %></td>
        <td><%= list.year_max %></td>
        <td><%= list.max %></td>
        <td><%= link_to 'Show', list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', lists_path %>
<h1 class="title">
  <strong><%= @list.country %></strong>
</h1>

<div class="country-data">
  <div>
    <p>
      <strong>Country code:</strong>
      <%= @list.country_code %>
    </p>

    <p>
      <strong>Region:</strong>
      <%= @list.region %>
    </p>

    <p>
      <strong>Income level:</strong>
      <%= @list.income_level %>
    </p>

    <p>
      <strong>Average emissions:</strong>
      <%= @list.average %>
      (tons) per capita
    </p>

    <p>
      <strong>Lowest year:</strong>
      <%= @list.year_min %>
    </p>

    <p>
      <strong>Lowest emisisons:</strong>
      <%= @list.min %>
      (tons) per capita
    </p>

    <p>
      <strong>Highest year:</strong>
      <%= @list.year_max %>
    </p>

    <p>
      <strong>Highest emisisons:</strong>
      <%= @list.max %>
      (tons) per capita
    </p>
  </div>
  <div class="data-graph">
    <%= column_chart [["1990", @list.year_one], ["1991", @list.year_two],
    ["1992", @list.year_three],["1993",@list.year_four],
    ["1994",@list.year_five],["1995",@list.year_six],
    ["1996",@list.year_seven],["1997",@list.year_eight],
    ["1998", @list.year_nine],["1999",@list.year_ten],
    ["2000",@list.year_eleven],["2001",@list.year_twelve],
    ["2002",@list.year_thirteen],["2003",@list.year_fourteen],
    ["2004", @list.year_fiveteen],["2005",@list.year_sixteen],
    ["2006",@list.year_seventeen],["2007",@list.year_eighteen],
    ["2008",@list.year_nineteen],["2009",@list.year_twenty],
    ["2010", @list.year_twentyone],["2011",@list.year_twentytwo],
    ["2012",@list.year_twentythree],["2013",@list.year_twentyfour],
    ["2014",@list.year_twentyfive],["2015",@list.year_twentysix],
    ["2016", @list.year_twentyseven],["2017",@list.year_twentyeight],
    ["2018",@list.year_twentynine],["2019",@list.year_thirty]]%>
  <div>
 </div>